import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ordenes Actuales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        <Head>
          <title>Hello world!</title>
          <meta
              http-equiv="Content-Security-Policy"
              content="upgrade-insecure-requests"
          />
        </Head>
      <html lang="en">
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
      <body className={inter.className}>{children}</body>
      </html>
      </>
  );
}
